title: Procesamiento del Lenguaje Natural
description: Carrera de Especialización en Inteligencia Artificial - Cohorte 16 - 2024
show_downloads: true
theme: jekyll-theme-architect
nav:
  - text: "Inicio"
    url: "/"
  - text: "D1"
    url: "/D1/"
  - text: "D2"
    url: "/D2/"
